import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const ENV_PATH = path.join(root, '.env');

export const REQUIRED_ENV = ['DB_USER', 'DB_NAME', 'ADMIN_EMAIL', 'ADMIN_PASSWORD', 'JWT_SECRET'];

const state = { configured: false };

export function isConfigured() {
  return state.configured;
}

export function markConfigured() {
  state.configured = true;
}

export function missingEnv(env = process.env) {
  return REQUIRED_ENV.filter((name) => !env[name]);
}

function quote(value) {
  const str = String(value);
  if (/[\r\n]/.test(str)) throw new Error('Values cannot contain line breaks');
  if (!str.includes("'")) return `'${str}'`;
  if (!str.includes('"')) return `"${str}"`;
  if (!str.includes('`')) return `\`${str}\``;
  throw new Error('Values cannot contain all three quote characters');
}

export function buildEnvFile(values) {
  const sections = [
    ['# ---- Server ----', ['NODE_ENV', 'BASE_URL']],
    ['# ---- MySQL ----', ['DB_HOST', 'DB_PORT', 'DB_USER', 'DB_PASSWORD', 'DB_NAME']],
    ['# ---- Admin login ----', ['ADMIN_EMAIL', 'ADMIN_PASSWORD', 'JWT_SECRET']],
  ];
  const lines = [`# Generated by the setup wizard on ${new Date().toISOString()}`, ''];
  for (const [heading, keys] of sections) {
    lines.push(heading);
    for (const key of keys) lines.push(`${key}=${quote(values[key] ?? '')}`);
    lines.push('');
  }
  const content = lines.join('\n');

  // Round-trip through dotenv so we never write a file that loads differently than intended.
  const parsed = dotenv.parse(content);
  for (const [key, value] of Object.entries(values)) {
    if (parsed[key] !== String(value ?? '')) throw new Error(`Value for ${key} cannot be stored safely`);
  }
  return content;
}

export function writeEnvFile(content) {
  if (fs.existsSync(ENV_PATH)) {
    fs.copyFileSync(ENV_PATH, `${ENV_PATH}.bak-${Date.now()}`);
  }
  fs.writeFileSync(ENV_PATH, content, { mode: 0o600 });
}
